### ISSUE TITLE
New Button Color

### ISSUE THREAD

**Issue by xuhang57** [cyverse/cyverse-ui#48]
Really like the how Button works right now. By any chance, cyverse-ui could support many different button colors besides what we have as primary and secondary right now? 

For example, maybe for delete raisedbutton, we could put it in red. 

Just a thought
Thanks!

**Comment by Tharon-C** [comment]
cyverse-ui is an extension of [material-ui](http://www.material-ui.com/#/), we use RaisedButton directly from there. It is possible to modify RaisedButton with the `backgroundColor` prop to get other colors.

For the case of danger I'd recommend FlatButton as it has less visual weight to it with just red text as opposed to the whole background being red which can be a bit loud.
