### ISSUE TITLE
Rename files with jsx

### ISSUE THREAD

**Issue by cdosborn** [cyverse/cyverse-ui#54]
Files with jsx should be renamed from `.js` -> `.jsx`. This will fix the ugly diffs.

**Comment by Tharon-C** [comment]
You are right. I'm always copying the cool kids but see no benefit in `.js` over `.jsx`.

Certainly the ugly diffs are enough reason to use `.jsx` though. I keep thinking they will fix that.

**Comment by Tharon-C** [comment]
I believe that the issue with GH's ugly diffs with `.jsx` syntax in `.js` has been fixed.

I'm not sure there is much value in renaming files anymore and Facebook seems to have taken the side of not using `.jsx`, observable by use of `.js` in react-create-app and this [change log](https://github.com/facebook/create-react-app/releases/tag/v0.4.1). This is still a controversial topic so this can certainly be reopened but closing for now.
