### ISSUE TITLE
[MediaCard] Rename subTitle prop to subtitle (it's a single word)

### ISSUE THREAD

**Issue by jchansen** [cyverse/cyverse-ui#79]
MediaCard has a property call `subTitle`. But subtitle is an actual word ([definition](http://www.dictionary.com/browse/subtitle)), so it doesn't need to be camel-case. It can just be `subtitle`.

**Comment by Tharon-C** [comment]
And Actually should be called "secondaryText" and "primaryText" as per MUI standard.
I'm making a PR to change several prop names on `MediaCard`

**Comment by Tharon-C** [comment]
#107 resolves this issue
