### ISSUE TITLE
[Guide] Break up organizational structure to have a component-per-route

### ISSUE THREAD

**Issue by jchansen** [cyverse/cyverse-ui#80]
There's weird performance issues where the site becomes slow to navigate (very delayed responses to clicks) or simply slow to perform.

Unclear what the root cause is, but it's difficult to isolate the issue when all the components are on a single page (i.e. identify which one(s) are causing the issue).

It also has the secondary effect of reducing confidence in the library, if the demo page is performing poorly.

I'm recommending breaking the Guide up to have a single component-per-route, to make sure each component owns the page it's displayed on, and can provide some semblance of guarantee about the experience it's demonstrating.

@Tharon-C has approved making this change. I'm writing it up here as a "todo" and assigning to myself.

**Comment by Tharon-C** [comment]
This is issue is resolved by #103
