### ISSUE TITLE
[Guide] Collapse code by default

### ISSUE THREAD

**Issue by jchansen** [cyverse/cyverse-ui#81]
I recommend collapsing the code in the Guide by default.

Especially when all components are on a single page, I often finding myself navigating to the Guide to search for a component, to see how it looks and behaves and whether I want to include it. But there's so much code on the page, it makes it difficult to scan and find what I'm looking for. The components end up feeling second to the code, where I think the idea is that they should be the focus, and only when I want to see how I want to implement one, do I care about the code.

Collapsing the code by default would make viewing it an opt-in behavior, like "Oh, I like this, let me expand this code snippet so I can copy it".

@Tharon-C has approved this change. I'm writing it down as a "todo" and assigning to myself.

**Comment by Tharon-C** [comment]
#103 resolves this issue
