### ISSUE TITLE
[CheckableAvatar] Can we make this compatible with ListItem from material-ui?

### ISSUE THREAD

**Issue by jchansen** [cyverse/cyverse-ui#82]
I like the `CheckableAvatar`, but it appears I can't use it as-is as a simple substitution for the `Avatar` in `material-ui`.

Is it supposed to be compatible, or is the expected/designed behavior such that is can only display properly within a `ListCard` from `cyverse-ui`?

This screenshot captures what happens when substituting `Avatar` for `CheckableAvatar` in a typical `ListItem` from `material-ui`. Code below. I expected the ListItem's to look identical, but 

<img width="1041" alt="avatar-vs-checkable-avatar" src="https://user-images.githubusercontent.com/2637399/34367531-2fbebcc2-ea69-11e7-97b0-071eef16a0be.png">

```jsx
<List>
  <ListItem 
    primaryText="LendardsWorld"
    secondaryText="Created Dec 13 2017"
    leftAvatar={(
      <CheckableAvatar
        image={
          <Avatar backgroundColor="tomato">
             L
          </Avatar>
        }
      />
    )}
  />
</List>
```

**Comment by Tharon-C** [comment]
I can take a look. Thanks

**Comment by Tharon-C** [comment]
#83 addresses some of the issues here and #106 documents interoperability requested in this issue.
