### ISSUE TITLE
Discussion: Best interface for Element

### ISSUE THREAD

**Issue by Tharon-C** [cyverse/cyverse-ui#84]
@cdosborn in PR #83 brings up questions around the interface for Element.

Q: `display` is exposed as prop but also can be changed via `style` so why do we expose both?

A: The short answer is that style is exposed regardless of what styles we may also expose through props as convenience.

That said, I'm not set on exposing `display` as prop being the best choice. I mainly do because it is often changed in layout. So by exposing it as a prop makes common occurrences of: 
```<Element display="flex" />``` 

more readable than:
```<Element style={{ display: "flex"}}/>```

this might not be a good enough reason though.  

It should also be noted that `hide` and soon `readableHide` are also setting the display property. These are more justifiable as they expect a `bool` so are very clean and convenient to do things like:
```<Thing hide={ !isHidden }/>```
or
```
<Label readableHide >
   Screen readers still see me
</Label>
```

`readableHide` sets more css that at is hard to infer what it is doing and so is even more justifiable.

The gist at this point is I'm willing to ditch `display` if it proves problematic.

**Comment by cdosborn** [comment]
Thanks for creating this

Your pro argument is that "its more readable". I think you're right. However, any interface which has more than one way to achieve a thing is poor.

```
// Obviously problematic, which one takes precedence?
<Element style={ display: "flex" } display="block" />

// Less obvious, what if the parent passes parentProps = {display: 'block'}?
<Element style={ display: "flex" } ...{parentProps} />
```

The latter example demonstrates that this interface makes it hard to write code that is obviously correct.

**Comment by cdosborn** [comment]
Another reason why it's problematic is that your Element component would now have to support every style attribute.

**Comment by cdosborn** [comment]
The props for a component are how you abstract the component and hide its internals. So its better to have  a `hidden` prop rather than a `display` prop which takes a css string.

**Comment by cdosborn** [comment]
So its like trivially more readable, but then someone looks at and thinks, gee that doesn't work anywhere else, are they actually reproducing all the style attributes? which ones can i use

**Comment by Tharon-C** [comment]
#103 and #105 improve Element interface and resolve this issue by eliminating props that duplicate style properties.
