### ISSUE TITLE
No lifecycle nor expectation of Prettier defined as expectation

### ISSUE THREAD

**Issue by lenards** [cyverse/cyverse-ui#92]
There is not automation for collaborators/contributors to use prettier for consistent formatting. 

I would think there would be a "script" command provided in the `package.json`. In addition, I would think we would see it as a development dependency in `package.json`. 

If `prettier` is installed globally, then would it not be effective in helping a team of contributors to be consistent with format.

**Comment by lenards** [comment]
I know people like to "tweak" and customize their local environments to their usage patterns and work flow. However, for this effort - I think there at least needs to be some guidance for the "how" code _should_ be formatted. 

I favor not installing globally. I believe that some of the Atmosphere team may use [`npm-run`](https://www.npmjs.com/package/npm-run) to execute ad hoc commands with executables from `./node_module/.bin` available on the `$PATH`. There is also [`npx`](https://www.npmjs.com/package/npx) that is also included in [`npm@5.2.0` (and beyond)](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b). 

There is a repository of awesome `npx` possibilities: [js-n/awesome-npx](https://github.com/js-n/awesome-npx#-useful)

**Comment by lenards** [comment]
Pull request #93 is made available for consideration given what is stated in this issue. 

Feel free to close if is not the desired direction.

**Comment by Tharon-C** [comment]
Thanks for doing this @lenards I fully support these efforts
