### ISSUE TITLE
[FloatingActionButton] Make wrapper container not required to obtain expected behavior

### ISSUE THREAD

**Issue by jchansen** [cyverse/cyverse-ui#95]
Currently creating a FloatingActionButton (and getting the expected positioning of the actions) requires wrapping the entire thing in a container, like this (taken from docs):

```jsx
<div style={{
   position: "absolute",
   right: "20px",
   top: "50%"
}}>
    <FAB
        secondary={true}
        actions={[
            {
                label: 'New Instance'
                render: (
                    <FloatingActionButton mini={true}>
                       <StorageIcon />
                    </FloatingActionButton>
                )
            }
        ]}
    />
</div>
```

If instead, I apply the positioning directly to the FAB (because I'm positioning that component) like this:

```jsx
<FAB
     style={{
        position: "absolute",
        right: "20px",
        top: "50%"
     }}
     secondary={true}
     actions={[
         {
             label: 'New Instance'
             render: (
                 <FloatingActionButton mini={true}>
                    <StorageIcon />
                 </FloatingActionButton>
             )
         }
     ]}
 />
```

I end up with this, where the actions are rendered in the middle of the page.

<img width="1148" alt="cyverse_ui" src="https://user-images.githubusercontent.com/2637399/35075494-8581ce08-fbb0-11e7-9035-0f4deb802d6f.png">

The behavior I expected was that the actions would appear below the FloatingActionButton.

Can we change the behavior of this component so that I can position the FAB, and the child actions automatically render underneath it, without having to wrap it in a container?

**Comment by jchansen** [comment]
Hmm...ignore this for now. I'll submit a PR for this at some point. I needed the ability to close the actions after I click on one, so I'm currently building out this component further, but also seeing if I can break it up like the `MediaCard` in the process, e.g. something like:

```jsx
<FloatingActionButton>
    <FloatingActionButtonActions>
        <FloatingActionButtonAction
            tooltip="New Instance"
            icon={<InstanceIcon/>}
            onClick={this.createInstance}
        />
        <FloatingActionButtonAction
            tooltip="New Volume"
            icon={<VolumeIcon/>}
            onClick={this.createVolume}
        />
    </FloatingActionButtonActions>
</FloatingActionButton>
```

We'll see where it ends up. I like this foundation though (what exists in the library).

**Comment by Tharon-C** [comment]
#103 resolves this issue. See (FAB docs)[http://cyverse-ui-next.surge.sh/components/floating-action-button-doc] for implementation. It is broken up as shown above.
